### ISSUE TITLE
a how-to for running CRATE?

### ISSUE THREAD

**Issue by monperrus** [Chat-Wane/CRATE#35]
I don't find in the README or the wiki a how-to for running CRATE.

**Comment by Chat-Wane** [comment]
Hi,

I suppose that you mean an how-to from a user point of view. I wanted to integrate that inside crate (see #30) but you are right: I should write it somewhere in the meantime.

**Comment by monperrus** [comment]
> I suppose that you mean an how-to from a user point of view.
yes. The readme is usually the typical place to find this.

thanks.

**Comment by Chat-Wane** [comment]
I consider the issue closed (be0190a). Do not hesitate to re-open it if you require more details.

Thanks for your insight!

**Comment by monperrus** [comment]
you mean that this issue will be handled when #30 will be done?

**Comment by Chat-Wane** [comment]
Na, I mean: I just updated the readme. Now it includes a 'get started' section for new users explaining how to create a document, share it, and so on.

#30 is a bit different since it's about integrating a tutorial within the application.

**Comment by monperrus** [comment]
I meant how to build and deploy one's own instance of CRATE

**Comment by Chat-Wane** [comment]
Ah ok, I misunderstood! I reopen the issue.

**Comment by Chat-Wane** [comment]
Okay done: https://github.com/Chat-Wane/CRATE#how-to-build

I didn't write about the installation of bower and lessc. Personnally, I used the node packet manager to install them.

Once again, you are welcome to reopen the issue if you think it lacks some details.
