### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by gedw99** [Chat-Wane/CRATE#5]
I amlooking for a crdt compliant system that allows modelling of data as entities this way.

Also an ice that allows collaborative editing in general.

This is for a project related to 3d cad.
So I need to allow the objects to be collabotated on :)

Its for PhD / research project.

Could you elaborate on the roadmap ?

**Comment by Chat-Wane** [comment]
Hi,
A very first pre-alpha version is now live on this repository. Still a lot TODO before it is actually usable. I will update the readme soon.
